import type { User, FileMetadata, DashboardStats, AuditLog } from '../types';

// Mock users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@example.com',
    role: 'admin',
    isActive: true,
    createdAt: '2024-01-15T10:00:00Z',
    lastLoginAt: '2026-03-05T08:30:00Z',
  },
  {
    id: '2',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'user',
    isActive: true,
    createdAt: '2024-02-01T14:20:00Z',
    lastLoginAt: '2026-03-04T16:45:00Z',
  },
  {
    id: '3',
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'user',
    isActive: true,
    createdAt: '2024-02-10T09:15:00Z',
    lastLoginAt: '2026-03-03T11:20:00Z',
  },
  {
    id: '4',
    name: 'Bob Wilson',
    email: 'bob@example.com',
    role: 'user',
    isActive: false,
    createdAt: '2024-01-20T12:30:00Z',
  },
];

// Mock files
export const mockFiles: FileMetadata[] = [
  {
    id: 'f1',
    originalName: 'customer_database.csv',
    mimeType: 'text/csv',
    size: 2458624,
    uploadedBy: '1',
    uploaderName: 'Admin User',
    uploadedAt: '2026-03-05T07:15:00Z',
    status: 'sanitized',
    entityCount: 156,
    entitiesByType: {
      EMAIL: 45,
      PHONE: 38,
      AADHAAR: 32,
      PAN: 25,
      ADDRESS: 16,
    },
    sanitizedAt: '2026-03-05T07:18:23Z',
    processingDuration: 203,
    riskScore: 'high',
  },
  {
    id: 'f2',
    originalName: 'employee_records.json',
    mimeType: 'application/json',
    size: 1245896,
    uploadedBy: '1',
    uploaderName: 'Admin User',
    uploadedAt: '2026-03-05T06:45:00Z',
    status: 'sanitized',
    entityCount: 89,
    entitiesByType: {
      EMAIL: 28,
      PHONE: 24,
      DOB: 18,
      ADDRESS: 12,
      PAN: 7,
    },
    sanitizedAt: '2026-03-05T06:47:12Z',
    processingDuration: 132,
    riskScore: 'medium',
  },
  {
    id: 'f3',
    originalName: 'transaction_log.sql',
    mimeType: 'application/sql',
    size: 5678912,
    uploadedBy: '1',
    uploaderName: 'Admin User',
    uploadedAt: '2026-03-05T05:30:00Z',
    status: 'processing',
    entityCount: 0,
    entitiesByType: {},
    riskScore: 'low',
  },
  {
    id: 'f4',
    originalName: 'patient_info.pdf',
    mimeType: 'application/pdf',
    size: 987456,
    uploadedBy: '1',
    uploaderName: 'Admin User',
    uploadedAt: '2026-03-04T18:20:00Z',
    status: 'sanitized',
    entityCount: 67,
    entitiesByType: {
      NAME: 22,
      PHONE: 18,
      EMAIL: 15,
      AADHAAR: 12,
    },
    sanitizedAt: '2026-03-04T18:23:45Z',
    processingDuration: 225,
    riskScore: 'high',
  },
  {
    id: 'f5',
    originalName: 'vendor_contacts.txt',
    mimeType: 'text/plain',
    size: 45632,
    uploadedBy: '1',
    uploaderName: 'Admin User',
    uploadedAt: '2026-03-04T15:10:00Z',
    status: 'sanitized',
    entityCount: 34,
    entitiesByType: {
      PHONE: 18,
      EMAIL: 16,
    },
    sanitizedAt: '2026-03-04T15:10:45Z',
    processingDuration: 45,
    riskScore: 'low',
  },
  {
    id: 'f6',
    originalName: 'hr_data.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 345678,
    uploadedBy: '1',
    uploaderName: 'Admin User',
    uploadedAt: '2026-03-04T12:00:00Z',
    status: 'error',
    entityCount: 0,
    entitiesByType: {},
    errorMsg: 'Failed to extract text from document',
    riskScore: 'low',
  },
  {
    id: 'f7',
    originalName: 'kyc_documents.csv',
    mimeType: 'text/csv',
    size: 1876543,
    uploadedBy: '1',
    uploaderName: 'Admin User',
    uploadedAt: '2026-03-03T14:30:00Z',
    status: 'sanitized',
    entityCount: 234,
    entitiesByType: {
      AADHAAR: 78,
      PAN: 68,
      PHONE: 45,
      EMAIL: 43,
    },
    sanitizedAt: '2026-03-03T14:34:56Z',
    processingDuration: 296,
    riskScore: 'high',
  },
];

// Mock dashboard stats
export const mockDashboardStats: DashboardStats = {
  totalFiles: 7,
  pendingFiles: 0,
  sanitizedFiles: 5,
  failedFiles: 1,
  processingFiles: 1,
  piiDetectionsByType: [
    { type: 'EMAIL', count: 210 },
    { type: 'PHONE', count: 161 },
    { type: 'AADHAAR', count: 122 },
    { type: 'PAN', count: 100 },
    { type: 'ADDRESS', count: 28 },
    { type: 'DOB', count: 18 },
    { type: 'NAME', count: 22 },
  ],
  recentActivity: [
    {
      id: 'f1',
      fileName: 'customer_database.csv',
      status: 'sanitized',
      timestamp: '2026-03-05T07:18:23Z',
      entityCount: 156,
    },
    {
      id: 'f2',
      fileName: 'employee_records.json',
      status: 'sanitized',
      timestamp: '2026-03-05T06:47:12Z',
      entityCount: 89,
    },
    {
      id: 'f3',
      fileName: 'transaction_log.sql',
      status: 'processing',
      timestamp: '2026-03-05T05:30:00Z',
      entityCount: 0,
    },
    {
      id: 'f4',
      fileName: 'patient_info.pdf',
      status: 'sanitized',
      timestamp: '2026-03-04T18:23:45Z',
      entityCount: 67,
    },
  ],
  topRiskFiles: [
    {
      id: 'f7',
      fileName: 'kyc_documents.csv',
      riskScore: 'high',
      entityCount: 234,
    },
    {
      id: 'f1',
      fileName: 'customer_database.csv',
      riskScore: 'high',
      entityCount: 156,
    },
    {
      id: 'f2',
      fileName: 'employee_records.json',
      riskScore: 'medium',
      entityCount: 89,
    },
  ],
};

// Mock audit logs
export const mockAuditLogs: AuditLog[] = [
  {
    id: 'a1',
    userId: '1',
    userEmail: 'admin@example.com',
    action: 'UPLOAD',
    fileId: 'f1',
    fileName: 'customer_database.csv',
    ipAddress: '192.168.1.100',
    timestamp: '2026-03-05T07:15:00Z',
  },
  {
    id: 'a2',
    userId: '1',
    userEmail: 'admin@example.com',
    action: 'SCAN_COMPLETE',
    fileId: 'f1',
    fileName: 'customer_database.csv',
    ipAddress: '192.168.1.100',
    timestamp: '2026-03-05T07:18:23Z',
    metadata: { entityCount: 156, duration: 203 },
  },
  {
    id: 'a3',
    userId: '1',
    userEmail: 'admin@example.com',
    action: 'DOWNLOAD_ORIGINAL',
    fileId: 'f1',
    fileName: 'customer_database.csv',
    ipAddress: '192.168.1.100',
    timestamp: '2026-03-05T07:20:15Z',
  },
  {
    id: 'a4',
    userId: '2',
    userEmail: 'john@example.com',
    action: 'DOWNLOAD_SANITIZED',
    fileId: 'f1',
    fileName: 'customer_database.csv',
    ipAddress: '192.168.1.105',
    timestamp: '2026-03-05T08:10:30Z',
  },
  {
    id: 'a5',
    userId: '1',
    userEmail: 'admin@example.com',
    action: 'LOGIN',
    ipAddress: '192.168.1.100',
    timestamp: '2026-03-05T08:30:00Z',
  },
  {
    id: 'a6',
    userId: '2',
    userEmail: 'john@example.com',
    action: 'ACCESS_DENIED',
    fileId: 'f1',
    fileName: 'customer_database.csv',
    ipAddress: '192.168.1.105',
    timestamp: '2026-03-05T09:45:00Z',
    metadata: { reason: 'Attempted to download original file' },
  },
  {
    id: 'a7',
    userId: '1',
    userEmail: 'admin@example.com',
    action: 'UPLOAD',
    fileId: 'f2',
    fileName: 'employee_records.json',
    ipAddress: '192.168.1.100',
    timestamp: '2026-03-05T06:45:00Z',
  },
];
